### PR TITLE
Graceful shutdown upon receiving CTRL-C when running with node

### PR DESCRIPTION
**Pull request by blu3mania**
Also improved Database.filterRooms() for slight performance gain.

### CODE REVIEW

**Comment by Billyzou0741326** [comment]
Do the worker processes quit upon termination of the master process? 
I didn't take into consideration the shutdown behavior on windows, and it seems like using cluster is not a good idea after all. Perhaps I should merge them into one process. Any thoughts?

**Comment by blu3mania** [comment]
> Do the worker processes quit upon termination of the master process?

Yes, child processes will be terminated when parent process exits. If graceful shutdown is required, SIGINT handler will need to trigger message to all children then wait for them to come back, which needs to be combined with parent process's own graceful shutdown promise before calling exit(). And to avoid lockup, some kind of timeout mechanism is required in case some children processes never respond back. I didn't check child process code but I doubt we need to do anything for them to gracefully shutdown anyway.

> I didn't take into consideration the shutdown behavior on windows, and it seems like using cluster is not a good idea after all. Perhaps I should merge them into one process. Any thoughts?

Totally agreed. Personally I would use worker threads which use less resources, and you don't need to worry about leaving zombie processes behind.

**Comment by blu3mania** [comment]
Though, if you plan to go with worker threads, node.js should be at least 11.7.0, or better, current LTS version 12.x. Right now you marked required node.js version as 10.16.3, which does not have worker threads support by default unless using --experimental-worker flag.

**Comment by Billyzou0741326** [comment]
Indeed, apprently worker threads are optimized for cpu intensive tasks, whereas clusters work well for distributing connections. Both approaches, however, introduce complexity in that they involve exchanging messages between the master and the workers and require extra steps in room distribution. I wonder if it's worth the trouble of spawning processes/threads and managing rooms for the efficiency. 

With those concerns, I took out the master-worker logic in the [TypeScript version](https://github.com/Billyzou0741326/bilibili-live-monitor-ts), which implies potential ineffiency.

**Pull request merged**
